export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const UPDATE_MOVIE_FORM_DATA = 'UPDATE_MOVIE_FORM_DATA';
export const CLEAR_MOVIE_FORM_DATA = 'CLEAR_MOVIE_FORM_DATA';
export const MOVIE_FORM_SUBMIT = 'MOVIE_FORM_SUBMIT';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';
export const REQUEST_FOR_MOVIES = 'REQUEST_FOR_MOVIES';
export const REQUEST_FOR_MOVIE = 'REQUEST_FOR_MOVIE';

export const UPDATE_USER_FORM_DATA = 'UPDATE_USER_FORM_DATA';
export const CLEAR_USER_FORM_DATA = 'CLEAR_USER_FORM_DATA';

export const CLEAR_SESSION_FORM_DATA = 'CLEAR_SESSION_FORM_DATA';
export const UPDATE_SESSION_FORM_DATA = 'UPDATE_SESSION_FORM_DATA';
export const REQUEST_FOR_SESSION = 'REQUEST_FOR_SESSION';
